// Generated by Framer (65e1cff)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "q6uln7", mediaQuery: "(min-width: 1440px)"}, {hash: "91fpmf", mediaQuery: "(min-width: 810px) and (max-width: 1439.98px)"}, {hash: "1r44tcg", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, framerSearch: {index: true}, robots: "max-image-preview:large", serializationId: "framer-lp99o", title: siteMetadata(params, activeLocale).title || "404", viewport: "width=device-width"}
}

export const metadataVersion = 1