// Generated by Framer (eaac66a)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1qit58p", mediaQuery: "(min-width: 1440px)"}, {hash: "cbel8a", mediaQuery: "(min-width: 810px) and (max-width: 1439.98px)"}, {hash: "1172iny", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {btBbhBuNJ: "faq", ddVMDuypM: "hero", eAHVSnUN1: "intro", FVleePLKb: "experience", g47fbrVBk: "process", H9oin6mZn: "about", n51p5zvOx: "process-cards", NGZWMJ3Kr: "about-1", uvQEUapsQ: "work", x5Ih1UQT4: "pricing", yrU5XJ4VY: "cta"}, framerSearch: {index: true}, robots: "max-image-preview:large", serializationId: "framer-uf72o", title: siteMetadata(params, activeLocale).title || "Home", viewport: "width=device-width"}
}

export const metadataVersion = 1