// Generated by Framer (86f5ff9)

import { addFonts, addPropertyControls, ControlType, cx, CycleVariantState, useActiveVariantCallback, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";

const cycleOrder = ["Bvngu5CEP", "Ij4n_Tyg9"];

const serializationHash = "framer-t80rX"

const variantClassNames = {Bvngu5CEP: "framer-v-1ewtnv7", Ij4n_Tyg9: "framer-v-3p24k8"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion.create(React.Fragment)

const humanReadableVariantMap = {Close: "Ij4n_Tyg9", Menu: "Bvngu5CEP"}

const getProps = ({height, id, tap, width, ...props}) => { return {...props, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "Bvngu5CEP", XKaY3MrGu: tap ?? props.XKaY3MrGu} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;variant?: keyof typeof humanReadableVariantMap;tap?: any; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const fallbackRef = useRef<HTMLElement>(null)

const refBinding = ref ?? fallbackRef

const defaultLayoutId = React.useId()

const { activeLocale, setLocale } = useLocaleInfo()

const componentViewport = useComponentViewport()

const {style, className, layoutId, variant, XKaY3MrGu, ...restProps} = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({cycleOrder, defaultVariant: "Bvngu5CEP", ref: refBinding, variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant)

const onTapc2fruv = activeVariantCallback(async (...args) => {
setGestureState({isPressed: false})
if (XKaY3MrGu) {const res = await XKaY3MrGu(...args);
if (res === false) return false;}
})

const sharedStyleClassNames = []

const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)

return (<LayoutGroup id={layoutId ?? defaultLayoutId}><Variants animate={variants} initial={false}><Transition value={transition1}><motion.div {...restProps} {...gestureHandlers} className={cx(scopingClassNames, "framer-1ewtnv7", className, classNames)} data-framer-name={"Menu"} data-highlight layoutDependency={layoutDependency} layoutId={"Bvngu5CEP"} onTap={onTapc2fruv} ref={refBinding} style={{backgroundColor: "var(--token-cd9f24d5-f0ad-4213-bead-63c4e991dc40, rgb(255, 255, 255))", borderBottomLeftRadius: 48, borderBottomRightRadius: 48, borderTopLeftRadius: 48, borderTopRightRadius: 48, ...style}} variants={{Ij4n_Tyg9: {backgroundColor: "rgba(255, 255, 255, 0.9)"}}} {...addPropertyOverrides({Ij4n_Tyg9: {"data-framer-name": "Close"}}, baseVariant, gestureVariant)}><motion.div className={"framer-1pldo3g"} data-framer-name={"Bottom"} layoutDependency={layoutDependency} layoutId={"E6F1sZXhH"} style={{backgroundColor: "var(--token-00af65c3-92fd-4f69-9228-cfe71d95f29a, rgb(0, 0, 0))", borderBottomLeftRadius: 10, borderBottomRightRadius: 10, borderTopLeftRadius: 10, borderTopRightRadius: 10, rotate: 0}} variants={{Ij4n_Tyg9: {rotate: -45}}}/><motion.div className={"framer-u50iwl"} data-framer-name={"Top"} layoutDependency={layoutDependency} layoutId={"lzXIb5zyS"} style={{backgroundColor: "var(--token-00af65c3-92fd-4f69-9228-cfe71d95f29a, rgb(0, 0, 0))", borderBottomLeftRadius: 10, borderBottomRightRadius: 10, borderTopLeftRadius: 10, borderTopRightRadius: 10, rotate: 0}} variants={{Ij4n_Tyg9: {rotate: 45}}}/></motion.div></Transition></Variants></LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-t80rX.framer-8opwal, .framer-t80rX .framer-8opwal { display: block; }", ".framer-t80rX.framer-1ewtnv7 { cursor: pointer; height: 44px; overflow: hidden; position: relative; width: 44px; will-change: var(--framer-will-change-override, transform); }", ".framer-t80rX .framer-1pldo3g { flex: none; height: 1px; left: calc(50.00000000000002% - 16px / 2); overflow: hidden; position: absolute; top: calc(59.090909090909115% - 1px / 2); width: 16px; will-change: var(--framer-will-change-override, transform); }", ".framer-t80rX .framer-u50iwl { flex: none; height: 1px; left: calc(50.00000000000002% - 16px / 2); overflow: hidden; position: absolute; top: calc(38.636363636363654% - 1px / 2); width: 16px; will-change: var(--framer-will-change-override, transform); }", ".framer-t80rX.framer-v-3p24k8.framer-1ewtnv7 { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 44px); }", ".framer-t80rX.framer-v-3p24k8 .framer-1pldo3g, .framer-t80rX.framer-v-3p24k8 .framer-u50iwl { top: calc(50.00000000000002% - 1px / 2); }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 44
 * @framerIntrinsicWidth 44
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Ij4n_Tyg9":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"XKaY3MrGu":"tap"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerdIXYQxBn4: React.ComponentType<Props> = withCSS(Component, css, "framer-t80rX") as typeof Component;
export default FramerdIXYQxBn4;

FramerdIXYQxBn4.displayName = "Menu Icon";

FramerdIXYQxBn4.defaultProps = {height: 44, width: 44};

addPropertyControls(FramerdIXYQxBn4, {variant: {options: ["Bvngu5CEP", "Ij4n_Tyg9"], optionTitles: ["Menu", "Close"], title: "Variant", type: ControlType.Enum}, XKaY3MrGu: {title: "Tap", type: ControlType.EventHandler}} as any)

addFonts(FramerdIXYQxBn4, [{explicitInter: true, fonts: []}], {supportsExplicitInterCodegen: true})