// Generated by Framer (86f5ff9)

import { addFonts, addPropertyControls, ComponentViewportProvider, ControlType, cx, CycleVariantState, getFonts, getFontsFromSharedStyle, getPropertyControls, RichText, SmartComponentScopedContainer, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import { Icon as Phosphor } from "https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/CAjjxbTJBxHwH1MagCef/Phosphor.js";
import { Icon as Phosphor1 } from "https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js";
import * as sharedStyle from "../css/xZndidUCt";
const PhosphorFonts = getFonts(Phosphor);
const Phosphor1Controls = getPropertyControls(Phosphor1);

const serializationHash = "framer-2IfhF"

const variantClassNames = {OBHE0mSc0: "framer-v-qz7qqb"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring"}

const animation = {filter: "blur(1px)", opacity: 0.001, rotate: 0, scale: 1, skewX: 0, skewY: 0, x: 0, y: 10}

const transition2 = {bounce: 0, delay: 0.02, duration: 0.2, type: "spring"}

const textEffect = {effect: animation, tokenization: "character", transition: transition2, trigger: "onInView", type: "appear"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion.create(React.Fragment)

const getProps = ({height, id, name1, title, width, ...props}) => { return {...props, UN_qTMiiO: title ?? props.UN_qTMiiO ?? "One Page with multiple sections", z_mjDIx1U: name1 ?? props.z_mjDIx1U ?? "House"} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;title?: string;name1?: string; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const fallbackRef = useRef<HTMLElement>(null)

const refBinding = ref ?? fallbackRef

const defaultLayoutId = React.useId()

const { activeLocale, setLocale } = useLocaleInfo()

const componentViewport = useComponentViewport()

const {style, className, layoutId, variant, UN_qTMiiO, z_mjDIx1U, ...restProps} = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({defaultVariant: "OBHE0mSc0", ref: refBinding, variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const sharedStyleClassNames = [sharedStyle.className]

const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)

return (<LayoutGroup id={layoutId ?? defaultLayoutId}><Variants animate={variants} initial={false}><Transition value={transition1}><motion.div {...restProps} {...gestureHandlers} className={cx(scopingClassNames, "framer-qz7qqb", className, classNames)} data-framer-name={"Variant 1"} layoutDependency={layoutDependency} layoutId={"OBHE0mSc0"} ref={refBinding} style={{...style}}><motion.div className={"framer-fi9lmq"} layoutDependency={layoutDependency} layoutId={"UdHomyHgI"}><ComponentViewportProvider ><SmartComponentScopedContainer className={"framer-4uce0c-container"} isModuleExternal layoutDependency={layoutDependency} layoutId={"w53q8gry7-container"} nodeId={"w53q8gry7"} rendersWithMotion scopeId={"Z2qQpgp9H"}><Phosphor color={"var(--token-00af65c3-92fd-4f69-9228-cfe71d95f29a, rgb(0, 0, 0))"} height={"100%"} iconSearch={"House"} iconSelection={z_mjDIx1U} id={"w53q8gry7"} layoutId={"w53q8gry7"} mirrored={false} selectByList style={{height: "100%", width: "100%"}} weight={"regular"} width={"100%"}/></SmartComponentScopedContainer></ComponentViewportProvider></motion.div><RichText __fromCanvasComponent children={<React.Fragment><motion.p className={"framer-styles-preset-21ogod"} data-styles-preset={"xZndidUCt"}>One Page with multiple sections</motion.p></React.Fragment>} className={"framer-1yednmm"} effect={textEffect} fonts={["Inter"]} layoutDependency={layoutDependency} layoutId={"O2h0ayG4T"} style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", "--framer-paragraph-spacing": "0px"}} text={UN_qTMiiO} verticalAlignment={"top"} withExternalLayout/></motion.div></Transition></Variants></LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-2IfhF.framer-en8rm5, .framer-2IfhF .framer-en8rm5 { display: block; }", ".framer-2IfhF.framer-qz7qqb { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 494px; }", ".framer-2IfhF .framer-fi9lmq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 1px 0px 0px 0px; position: relative; width: 24px; }", ".framer-2IfhF .framer-4uce0c-container { flex: none; height: 24px; position: relative; width: 24px; }", ".framer-2IfhF .framer-1yednmm { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-2IfhF.framer-qz7qqb, .framer-2IfhF .framer-fi9lmq { gap: 0px; } .framer-2IfhF.framer-qz7qqb > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-2IfhF.framer-qz7qqb > :first-child, .framer-2IfhF .framer-fi9lmq > :first-child { margin-left: 0px; } .framer-2IfhF.framer-qz7qqb > :last-child, .framer-2IfhF .framer-fi9lmq > :last-child { margin-right: 0px; } .framer-2IfhF .framer-fi9lmq > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }", ...sharedStyle.css]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 27
 * @framerIntrinsicWidth 494
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"UN_qTMiiO":"title","z_mjDIx1U":"name1"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerZ2qQpgp9H: React.ComponentType<Props> = withCSS(Component, css, "framer-2IfhF") as typeof Component;
export default FramerZ2qQpgp9H;

FramerZ2qQpgp9H.displayName = "row";

FramerZ2qQpgp9H.defaultProps = {height: 27, width: 494};

addPropertyControls(FramerZ2qQpgp9H, {UN_qTMiiO: {defaultValue: "One Page with multiple sections", displayTextArea: false, title: "Title", type: ControlType.String}, z_mjDIx1U: Phosphor1Controls?.["iconSelection"] && {...Phosphor1Controls["iconSelection"], defaultValue: "House", description: undefined, hidden: undefined, title: "Name"}} as any)

addFonts(FramerZ2qQpgp9H, [{explicitInter: true, fonts: [{family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F", url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116", url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+1F00-1FFF", url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0370-03FF", url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF", url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD", url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB", url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2", weight: "400"}]}, ...PhosphorFonts, ...getFontsFromSharedStyle(sharedStyle.fonts)], {supportsExplicitInterCodegen: true})